spring.application.name=tournamnet
spring.datasource.url=jdbc:postgresql://ep-snowy-bonus-a1djxf96-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_dGwDJS2LjMH3
spring.datasource.driver-class-name=org.postgresql.Driver
spring.thymeleaf.check-template-location=false


## JPA Config
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# Crucial for your case raise parts limit (fields + files)
server.tomcat.max-part-count=100


spring.security.user.name=admin
spring.security.user.password=homer


##Make The Console Utf-8
logging.charset.console=UTF-8
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.force=true



# The path and name of the log file
logging.file.name=logs/tournament-app.log

# How many days of history to keep
logging.logback.rollingpolicy.max-history=7

# Max size of a single log file before it creates a new one
logging.logback.rollingpolicy.max-file-size=10MB

# Total size of all log files combined
logging.logback.rollingpolicy.total-size-cap=100MB

logging.charset.file=UTF-8

##cloudinary.url=cloudinary://227596885659777:P4Mi9fN3ioK2cx5re9Bwzg0eS5w@duvd5mzmk
##cloudinary.cloud-name=duvd5mzmk
##cloudinary.api-key=227596885659777
##cloudinary.api-secret=P4Mi9fN3ioK2cx5re9Bwzg0eS5w