spring.application.name=tournamnet
spring.datasource.url=jdbc:postgresql://ep-snowy-bonus-a1djxf96-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_dGwDJS2LjMH3
spring.datasource.driver-class-name=org.postgresql.Driver
spring.thymeleaf.check-template-location=false


## JPA Config
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# Crucial for your case raise parts limit (fields + files)
server.tomcat.max-part-count=100


spring.security.user.name=admin
spring.security.user.password=homer


##cloudinary.url=cloudinary://227596885659777:P4Mi9fN3ioK2cx5re9Bwzg0eS5w@duvd5mzmk
##cloudinary.cloud-name=duvd5mzmk
##cloudinary.api-key=227596885659777
##cloudinary.api-secret=P4Mi9fN3ioK2cx5re9Bwzg0eS5w